Add new meta
gear-dapps/fungible-token pull request #29
Opened 2023-01-06 13:28 UTC by azoyan

2023-01-09 09:01 UTC, bezrazli4n0 requested changes
Looks like `state/src/lib.rs` is empty

2023-01-16 09:57 UTC, LouiseMedova approved these changes

2023-01-16 13:09 UTC, fluiderson approved these changes

2023-01-16 13:09 UTC, fluiderson commented on io/Cargo.toml
> +gmeta = { git = "https://github.com/gear-tech/gear", features = ["codegen"] }
```suggestion
gmeta = { git = "https://github.com/gear-tech/gear" }
```
This feature makes sense only in the "state" crate because the feature enables the `#[metawasm]` macro.

2023-01-16 13:09 UTC, fluiderson commented on Cargo.toml
> +gmeta = { git = "https://github.com/gear-tech/gear", features = ["codegen"] }
```suggestion
gmeta = { git = "https://github.com/gear-tech/gear" }
```
See the previous comment.

2023-01-16 13:09 UTC, fluiderson commented on .metahash
> +[55, 246, 112, 45, 1, 166, 24, 239, 114, 15, 5, 185, 36, 161, 211, 114, 75, 104, 220, 248, 185, 39, 82, 171, 207, 103, 252, 158, 199, 147, 161, 171]
Add this file to `.gitignore`. It's only needed during building.

2023-01-29 12:47 UTC, bezrazli4n0 approved these changes

2023-01-29 18:30 UTC, merged